-- Note DATABASE Name as COllAGE and Role COllEGE

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE HCL_TRAINING;

-- IT IS just for showing what happend in the code, but i was do it manually CREATE DB And Schema.
-- Create Database + Schema
CREATE OR REPLACE DATABASE COLLAGE_DB;
CREATE OR REPLACE SCHEMA COLLAGE_DB.ACADEMICS;

SHOW WAREHOUSES;


-- Create Roles

CREATE OR REPLACE ROLE COLLEGE_ADMIN;
CREATE OR REPLACE ROLE FACULTY_ROLE;


-- Create Users

CREATE OR REPLACE USER admin_user
  PASSWORD = 'Admin@123'
  DEFAULT_ROLE = COLLEGE_ADMIN
  MUST_CHANGE_PASSWORD = TRUE;

CREATE OR REPLACE USER faculty_user
  PASSWORD = 'Faculty@123'
  DEFAULT_ROLE = FACULTY_ROLE
  MUST_CHANGE_PASSWORD = TRUE;



-- Assign roles to users

GRANT ROLE COLLEGE_ADMIN TO USER admin_user;
GRANT ROLE FACULTY_ROLE TO USER faculty_user;


-- Grant privileges to COLLEGE_ADMIN (Full Access)
-- Grant database usage
GRANT USAGE ON DATABASE COLLAGE_DB TO ROLE COLLEGE_ADMIN;

-- Grant schema full control
GRANT USAGE ON SCHEMA COLLAGE_DB.ACADEMICS TO ROLE COLLEGE_ADMIN;

GRANT CREATE TABLE, CREATE VIEW, CREATE STAGE, CREATE FILE FORMAT
ON SCHEMA COLLAGE_DB.ACADEMICS TO ROLE COLLEGE_ADMIN;


--Allow full table operations (for all tables)
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA COLLAGE_DB.ACADEMICS
TO ROLE COLLEGE_ADMIN;

GRANT ALL PRIVILEGES ON FUTURE TABLES IN SCHEMA COLLAGE_DB.ACADEMICS
TO ROLE COLLEGE_ADMIN;


-- Grant READ-ONLY privileges to FACULTY_ROLE
-- Allow them to “see” the DB + schema
GRANT USAGE ON DATABASE COLLAGE_DB TO ROLE FACULTY_ROLE;
GRANT USAGE ON SCHEMA COLLAGE_DB.ACADEMICS TO ROLE FACULTY_ROLE;

-- Give SELECT-only on tables
GRANT SELECT ON ALL TABLES IN SCHEMA COLLAGE_DB.ACADEMICS
TO ROLE FACULTY_ROLE;

GRANT SELECT ON FUTURE TABLES IN SCHEMA COLLAGE_DB.ACADEMICS
TO ROLE FACULTY_ROLE;


-- Role Hierarchy / Faculty Role accessible by admin
GRANT ROLE FACULTY_ROLE TO ROLE COLLEGE_ADMIN;


-- Testing
USE ROLE ACCOUNTADMIN;
GRANT ROLE COLLEGE_ADMIN TO USER AKHIL7777;

-- Test with COLLEGE_ADMIN
USE ROLE COLLEGE_ADMIN;
USE DATABASE COLLAGE_DB;
USE SCHEMA ACADEMICS;

CREATE OR REPLACE TABLE STUDENTS (
  ID INT,
  NAME STRING,
  DEPT STRING
);

INSERT INTO STUDENTS VALUES (1,'Akhil','CSE');


-- Test with FACULTY_ROLE
USE ROLE FACULTY_ROLE;
USE DATABASE COLLAGE_DB;
USE SCHEMA ACADEMICS;

SELECT * FROM STUDENTS;

-- Now try to create table by faculty
CREATE TABLE TEST1(ID INT);


-- Proof of work
-- Show roles
SHOW ROLES LIKE '%COLLEGE%';
SHOW ROLES LIKE '%FACULTY%';

-- Show grants
SHOW GRANTS TO ROLE COLLEGE_ADMIN;
SHOW GRANTS TO ROLE FACULTY_ROLE;

-- Show users
SHOW USERS LIKE '%user%';




